#!/usr/bin/env bash
# Updates ai-workflow-stats.js with real project metrics.
# Run from repo root: ./scripts/update-showcase-stats.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/ai-workflow-stats.js"

prs=$(gh pr list --repo bct8925/sftools --state merged --limit 500 --json number | jq length)
loc=$(git -C "$REPO_ROOT" ls-files | xargs wc -l 2>/dev/null | tail -1 | awk '{printf "%d", $1/1000}')
sessions=$(find ~/.claude/projects/-Users-briantaylor-dev-sftools -maxdepth 1 -name '*.jsonl' 2>/dev/null | wc -l | tr -d ' ')
specs=$(( $(find "$REPO_ROOT/openspec/specs" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ') + $(find "$REPO_ROOT/openspec/changes/archive" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ') ))

cat > "$OUT" <<EOF
// Auto-generated by scripts/update-showcase-stats.sh
window.SHOWCASE_STATS = { prs: $prs, loc: $loc, sessions: $sessions, specs: $specs };
EOF

echo "Updated $OUT:"
cat "$OUT"

# Also update the sftools.dev site if present
SITE_DIR="$REPO_ROOT/../sftools.dev/public"
if [ -d "$SITE_DIR" ]; then
    cp "$OUT" "$SITE_DIR/ai-workflow-stats.js"
    cp "$REPO_ROOT/ai-workflow-showcase.html" "$SITE_DIR/ai.html"
    echo "Synced to $SITE_DIR"
fi
