#!/usr/bin/env node

/**
 * Native Host Manifest Installer
 *
 * Installs the native messaging host manifest for Chrome/Chromium browsers.
 * This allows the sftools extension to communicate with the local proxy.
 *
 * Usage:
 *   node install.js [extension-id]
 *
 * If extension-id is not provided, it will prompt or use a default.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const readline = require('readline');

const HOST_NAME = 'com.sftools.proxy';

/**
 * Compute extension ID from the public key in manifest.json
 * Chrome uses the first 32 chars of SHA256(key) mapped to a-p
 */
function computeExtensionId(publicKeyBase64) {
    const keyBuffer = Buffer.from(publicKeyBase64, 'base64');
    const hash = crypto.createHash('sha256').update(keyBuffer).digest();
    const chars = 'abcdefghijklmnop';
    let id = '';
    for (let i = 0; i < 16; i++) {
        const byte = hash[i];
        id += chars[byte >> 4];
        id += chars[byte & 0x0f];
    }
    return id;
}

/**
 * Try to read extension ID from the extension's manifest.json
 */
function getExtensionIdFromManifest() {
    try {
        const manifestPath = path.join(__dirname, '..', 'manifest.json');
        const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
        if (manifest.key) {
            return computeExtensionId(manifest.key);
        }
    } catch (err) {
        // Ignore - manifest not found or no key
    }
    return null;
}

/**
 * Get the native messaging hosts directory for the current OS
 */
function getHostsDirectory() {
    const platform = os.platform();
    const home = os.homedir();

    switch (platform) {
        case 'darwin':
            return path.join(home, 'Library', 'Application Support', 'Google', 'Chrome', 'NativeMessagingHosts');
        case 'linux':
            return path.join(home, '.config', 'google-chrome', 'NativeMessagingHosts');
        case 'win32':
            return path.join(home, 'AppData', 'Local', 'Google', 'Chrome', 'User Data', 'NativeMessagingHosts');
        default:
            throw new Error(`Unsupported platform: ${platform}`);
    }
}

/**
 * Create the native host manifest
 */
function createManifest(extensionId) {
    // Use shell wrapper on Unix, direct node script on Windows
    const scriptPath = os.platform() === 'win32'
        ? path.resolve(__dirname, 'src', 'index.js')
        : path.resolve(__dirname, 'sftools-proxy.sh');

    return {
        name: HOST_NAME,
        description: 'sftools Local Proxy - enables gRPC and bypasses CORS for Salesforce API calls',
        path: scriptPath,
        type: 'stdio',
        allowed_origins: [
            `chrome-extension://${extensionId}/`
        ]
    };
}

/**
 * Find the node executable path
 */
function findNodePath() {
    const { execSync } = require('child_process');
    try {
        // Try to get node path from shell
        const nodePath = execSync('which node', { encoding: 'utf8' }).trim();
        if (nodePath && fs.existsSync(nodePath)) {
            return nodePath;
        }
    } catch (err) {
        // Ignore
    }

    // Common locations
    const commonPaths = [
        '/opt/homebrew/bin/node',
        '/usr/local/bin/node',
        '/usr/bin/node'
    ];

    for (const p of commonPaths) {
        if (fs.existsSync(p)) {
            return p;
        }
    }

    return 'node'; // Fall back to PATH lookup
}

/**
 * Create the shell wrapper script with correct node path
 * Uses ~/bin to avoid macOS security restrictions on scripts in Documents/Downloads
 */
function createWrapperScript(nodePath) {
    const userBin = path.join(os.homedir(), 'bin');
    const wrapperPath = path.join(userBin, 'sftools-proxy');
    const scriptDir = path.resolve(__dirname);

    // Create ~/bin if it doesn't exist
    if (!fs.existsSync(userBin)) {
        fs.mkdirSync(userBin, { recursive: true });
        console.log(`Created directory: ${userBin}`);
    }

    const content = `#!/bin/bash
# Native messaging host wrapper for sftools-proxy
# Auto-generated by install.js

NODE_PATH="${nodePath}"
SCRIPT_DIR="${scriptDir}"

cd "$SCRIPT_DIR"
exec "$NODE_PATH" "$SCRIPT_DIR/src/index.js" 2>> /tmp/sftools-proxy.log
`;

    fs.writeFileSync(wrapperPath, content);
    fs.chmodSync(wrapperPath, '755');

    // Clear any quarantine attributes
    try {
        require('child_process').execSync(`xattr -c "${wrapperPath}"`, { stdio: 'ignore' });
    } catch (err) {
        // Ignore if xattr fails
    }

    return wrapperPath;
}

/**
 * Install the manifest file
 */
function installManifest(extensionId) {
    const hostsDir = getHostsDirectory();
    const manifestPath = path.join(hostsDir, `${HOST_NAME}.json`);

    // On Unix, create wrapper script with detected node path
    if (os.platform() !== 'win32') {
        const nodePath = findNodePath();
        console.log(`Detected Node.js: ${nodePath}`);
        createWrapperScript(nodePath);
    }

    const manifest = createManifest(extensionId);

    // Create hosts directory if it doesn't exist
    if (!fs.existsSync(hostsDir)) {
        fs.mkdirSync(hostsDir, { recursive: true });
        console.log(`Created directory: ${hostsDir}`);
    }

    // Write manifest file
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
    console.log(`\nManifest installed: ${manifestPath}`);

    // Make the main script executable on Unix
    if (os.platform() !== 'win32') {
        const scriptPath = path.resolve(__dirname, 'src', 'index.js');
        fs.chmodSync(scriptPath, '755');
    }

    // Windows requires registry entry
    if (os.platform() === 'win32') {
        console.log('\n⚠️  Windows requires a registry entry for native messaging.');
        console.log('Run this command in an elevated PowerShell:');
        console.log(`\n  reg add "HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts\\${HOST_NAME}" /ve /t REG_SZ /d "${manifestPath}" /f\n`);
    }

    return manifestPath;
}

/**
 * Uninstall the manifest file
 */
function uninstallManifest() {
    const hostsDir = getHostsDirectory();
    const manifestPath = path.join(hostsDir, `${HOST_NAME}.json`);

    if (fs.existsSync(manifestPath)) {
        fs.unlinkSync(manifestPath);
        console.log(`Removed: ${manifestPath}`);

        if (os.platform() === 'win32') {
            console.log('\nTo complete uninstallation on Windows, run:');
            console.log(`\n  reg delete "HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts\\${HOST_NAME}" /f\n`);
        }
    } else {
        console.log('Manifest not found - nothing to uninstall');
    }
}

/**
 * Prompt user for input
 */
function prompt(question) {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    return new Promise((resolve) => {
        rl.question(question, (answer) => {
            rl.close();
            resolve(answer.trim());
        });
    });
}

/**
 * Main installation flow
 */
async function main() {
    const args = process.argv.slice(2);

    // Handle uninstall
    if (args.includes('--uninstall') || args.includes('-u')) {
        uninstallManifest();
        return;
    }

    console.log('sftools Native Host Installer\n');

    // Try to get extension ID
    let extensionId = args[0];

    if (!extensionId) {
        // Try to compute from manifest.json key
        extensionId = getExtensionIdFromManifest();
        if (extensionId) {
            console.log(`Found extension ID from manifest.json: ${extensionId}`);
        }
    }

    if (!extensionId) {
        // Prompt user
        console.log('To find your extension ID:');
        console.log('1. Go to chrome://extensions/');
        console.log('2. Enable "Developer mode"');
        console.log('3. Find "Salesforce Dev Tools" and copy its ID\n');

        extensionId = await prompt('Enter extension ID: ');

        if (!extensionId) {
            console.error('Error: Extension ID is required');
            process.exit(1);
        }
    }

    // Validate extension ID format (32 lowercase letters)
    if (!/^[a-p]{32}$/.test(extensionId)) {
        console.error('Error: Invalid extension ID format');
        console.error('Extension IDs are 32 characters using only letters a-p');
        process.exit(1);
    }

    // Install
    console.log(`\nInstalling native host for extension: ${extensionId}`);
    const manifestPath = installManifest(extensionId);

    console.log('\n✓ Installation complete!');
    console.log('\nNext steps:');
    console.log('1. Restart Chrome if it was running');
    console.log('2. Open sftools and go to Settings');
    console.log('3. Click "Connect to Proxy" to verify the connection');
}

main().catch((err) => {
    console.error('Installation failed:', err.message);
    process.exit(1);
});
