#!/bin/bash
# Native messaging host wrapper for sftools-proxy
# Auto-generated by install.js

NODE_PATH="/opt/homebrew/bin/node"
SCRIPT_DIR="/Users/bctaylor/Dev/sftools/sftools-proxy"

exec "$NODE_PATH" "$SCRIPT_DIR/src/index.js"
